/**
 *
 * Do not edit this file
 *
*/
import React from 'react';
import ReactDOM from 'react-dom';
import AdoptionAgency from './components/AdoptionAgency';

ReactDOM.render(
  <AdoptionAgency />,
  document.getElementById('app')
);
